### ISSUE TITLE
1.2.1 TODO List

### ISSUE THREAD

**Issue by chorton2227** [chorton2227/WP-Glossary-Hover#6]
- [x] Update class-tooltip-parser.php #3 
 - [x] Additional border-style #7
 - [x] Remove extra markup `<html><body></body></html>` generated by DomDocument.
 - [x] Investigate DomDocument [selector](https://github.com/chorton2227/WP-Glossary-Hover/blob/1.2.1/public/includes/class-tooltip-parser.php#L267)
 - [x] Update version
   - [x] Add @since version to new functions and variables
   - [x] Update plugin version
   - [x] Update WP version
 - [x] Update changelog
 - [x] Update language files
 - [x] Add naofireblade as a contributor

**Comment by chorton2227** [comment]
The `<p>` tag is added automatically, when loading html...
```
$source = 'test';
$doc = new DOMDocument();
$doc->loadHTML($source);
echo $doc->saveHTML(); // <html><body><p>test</p></body></html>
```
Unless the `<html>` and `<body>` tags already exist...
```
$source = '<html><body>test</body></html>';
$doc = new DOMDocument();
$doc->loadHTML($source);
echo $doc->saveHTML(); // <html><body>test</body></html>
```

**Comment by chorton2227** [comment]
Clean up html b555011c0a0a659f2323d9c03651f771001c10fd

**Comment by chorton2227** [comment]
Decode html entities and add as html 805ebb52008bcd8085ee89f9bb33e2186a6fee97

**Comment by chorton2227** [comment]
Updated version ab52fbb2a7b7a046d126fa74927d4031af9ae448
Updated readme d176eaaefe0a0a7ea3b3e119ed98a294024f8b2a
Update language files 8c6a4c9051fb026d6d5c06e346667c494a34511c

**Comment by chorton2227** [comment]
@naofireblade what is your userid on wordpress.org, so I can add you as a contributor in the README.txt.

**Comment by naofireblade** [comment]
Thanks, I'm now registered as naofireblade.

**Comment by chorton2227** [comment]
Add naofireblade as a contributor ad336d455da596b9f860d5a7919a5cbfaa211d3a
